version: '3.7'
services:
  backend:
    image: manhwalab-app:manhwalab
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5433/aron
      - SPRING_DATASOURCE_USERNAME=aron
      - SPRING_DATASOURCE_PASSWORD=Sisakvirag17
    depends_on:
      - database
    ports:
      - "8080:8080"
    expose:
      - "8080"

  database:
    image: manhwalab-database:manhwalab-db
    restart: always
    environment:
      - POSTGRES_USER=aron
      - POSTGRES_PASSWORD=Sisakvirag17
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
