version: '3.7'
services:
  backend:
    image: manhwalab-app:manhwalab
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/username
      - DB_USERNAME=
      - DB_PASSWORD=
    depends_on:
      - database
    ports:
      - "8080:8080"
    expose:
      - "8080"

  database:
    image: manhwalab-database:manhwalab-db
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: manhwalab-frontend:manhwalab-fr
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:8080"
    expose:
      - "8081"